site_name: Narrative LLM Tools Documentation
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/narrative-io/narrative-llm-tools

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Guides:
    - REST API Client: guides/rest-api-client.md
    - Conversation State: guides/conversation-state.md
    - JSON Schema Tools: guides/json-schema-tools.md
    - Format Enforcer: guides/format-enforcer.md
  - Components:
    - HuggingFace Handler: components/huggingface-handler.md
    - Templates: components/templates.md
  - Reward Functions: reward_functions/index.md
  - API Reference:
    - REST API Client: api/rest-api-client.md
    - State Management: api/state.md
    - Tools: api/tools.md
    - Utils: api/utils.md
  - Development:
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
